# Generated by Django 4.2 on 2024-10-23 21:34

import courses.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('dead_time', models.DateTimeField(blank=True, null=True, verbose_name='Dead Time')),
            ],
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['upload_date']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['chapter']},
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.file_path_image, verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='courses.exam', verbose_name='Exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question', verbose_name='Question')),
            ],
            options={
                'unique_together': {('exam', 'question')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(blank=True, through='courses.ExamQuestion', to='courses.question', verbose_name='Questions'),
        ),
    ]
